import 'package:flutter/material.dart';
import 'package:flutter/foundation.dart';
import 'package:shared_preferences/shared_preferences.dart';

const _kLocaleStorageKey = '__locale_key__';

class FFLocalizations {
  FFLocalizations(this.locale);

  final Locale locale;

  static FFLocalizations of(BuildContext context) =>
      Localizations.of<FFLocalizations>(context, FFLocalizations)!;

  static List<String> languages() => ['en', 'hi', 'pa', 'te', 'ta', 'bn'];

  static late SharedPreferences _prefs;
  static Future initialize() async =>
      _prefs = await SharedPreferences.getInstance();
  static Future storeLocale(String locale) =>
      _prefs.setString(_kLocaleStorageKey, locale);
  static Locale? getStoredLocale() {
    final locale = _prefs.getString(_kLocaleStorageKey);
    return locale != null && locale.isNotEmpty ? createLocale(locale) : null;
  }

  String get languageCode => locale.toString();
  String? get languageShortCode =>
      _languagesWithShortCode.contains(locale.toString())
          ? '${locale.toString()}_short'
          : null;
  int get languageIndex => languages().contains(languageCode)
      ? languages().indexOf(languageCode)
      : 0;

  String getText(String key) =>
      (kTranslationsMap[key] ?? {})[locale.toString()] ?? '';

  String getVariableText({
    String? enText = '',
    String? hiText = '',
    String? paText = '',
    String? teText = '',
    String? taText = '',
    String? bnText = '',
  }) =>
      [enText, hiText, paText, teText, taText, bnText][languageIndex] ?? '';

  static const Set<String> _languagesWithShortCode = {
    'ar',
    'az',
    'ca',
    'cs',
    'da',
    'de',
    'dv',
    'en',
    'es',
    'et',
    'fi',
    'fr',
    'gr',
    'he',
    'hi',
    'hu',
    'it',
    'km',
    'ku',
    'mn',
    'ms',
    'no',
    'pt',
    'ro',
    'ru',
    'rw',
    'sv',
    'th',
    'uk',
    'vi',
  };
}

class FFLocalizationsDelegate extends LocalizationsDelegate<FFLocalizations> {
  const FFLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) {
    final language = locale.toString();
    return FFLocalizations.languages().contains(
      language.endsWith('_')
          ? language.substring(0, language.length - 1)
          : language,
    );
  }

  @override
  Future<FFLocalizations> load(Locale locale) =>
      SynchronousFuture<FFLocalizations>(FFLocalizations(locale));

  @override
  bool shouldReload(FFLocalizationsDelegate old) => false;
}

Locale createLocale(String language) => language.contains('_')
    ? Locale.fromSubtags(
        languageCode: language.split('_').first,
        scriptCode: language.split('_').last,
      )
    : Locale(language);

final kTranslationsMap = <Map<String, Map<String, String>>>[
  // HomePage
  {
    'd39snm5w': {
      'en': 'Search User',
      'bn': 'ব্যবহারকারী অনুসন্ধান করুন',
      'hi': 'उपयोगकर्ता खोजें',
      'pa': 'ਖੋਜ ਉਪਭੋਗਤਾ',
      'ta': 'தேடல் பயனர்',
      'te': 'శోధన వినియోగదారు',
    },
    'gx7n4ftx': {
      'en': 'Search for users',
      'bn': 'ব্যবহারকারীদের জন্য অনুসন্ধান করুন',
      'hi': 'उपयोगकर्ताओं को खोजें',
      'pa': 'ਉਪਭੋਗਤਾਵਾਂ ਲਈ ਖੋਜ ਕਰੋ',
      'ta': 'பயனர்களைத் தேடுங்கள்',
      'te': 'వినియోగదారుల కోసం శోధించండి',
    },
    'hxfi0o86': {
      'en': 'Recent Users',
      'bn': 'সাম্প্রতিক ব্যবহারকারী',
      'hi': 'हाल के उपयोगकर्ता',
      'pa': 'ਹਾਲੀਆ ਉਪਭੋਗਤਾ',
      'ta': 'சமீபத்திய பயனர்கள்',
      'te': 'ఇటీవలి వినియోగదారులు',
    },
    'eys85ujb': {
      'en': 'see all',
      'bn': 'সবগুলো দেখ',
      'hi': 'सभी देखें',
      'pa': 'ਸਾਰੇ ਦੇਖੋ',
      'ta': 'அனைத்தையும் பார்',
      'te': 'అన్నింటిని చూడు',
    },
    '5ne9iog0': {
      'en': 'Group Chat',
      'bn': 'গ্রুপ চ্যাট',
      'hi': 'समूह बातचीत',
      'pa': 'ਗਰੁੱਪ ਚੈਟ',
      'ta': 'குழு அரட்டை',
      'te': 'గ్రూప్ చాట్',
    },
    '0tel0hed': {
      'en': 'Create',
      'bn': 'সৃষ্টি',
      'hi': 'बनाएं',
      'pa': 'ਬਣਾਓ',
      'ta': 'உருவாக்கு',
      'te': 'సృష్టించు',
    },
    'menzaya4': {
      'en': 'AksharAI',
      'bn': 'অক্ষরাই',
      'hi': 'अक्षराई',
      'pa': 'ਅਕਸ਼ਰਾਯ',
      'ta': 'அக்ஷராஐ',
      'te': 'అక్షరై',
    },
    'mj21k8ub': {
      'en': 'Home',
      'bn': 'বাড়ি',
      'hi': 'घर',
      'pa': 'ਘਰ',
      'ta': 'வீடு',
      'te': 'హోమ్',
    },
  },
  // RecentUser
  {
    't3hcw0fv': {
      'en': 'Recent Users',
      'bn': 'সক্রিয় ব্যবহারকারী',
      'hi': 'सक्रिय उपयोगकर्ता',
      'pa': 'ਕਿਰਿਆਸ਼ੀਲ ਉਪਭੋਗਤਾ',
      'ta': 'செயலில் உள்ள பயனர்கள்',
      'te': 'క్రియాశీల వినియోగదారులు',
    },
    'n1mtegi6': {
      'en': 'Search User',
      'bn': 'ব্যবহারকারী অনুসন্ধান করুন',
      'hi': 'उपयोगकर्ता खोजें',
      'pa': 'ਖੋਜ ਉਪਭੋਗਤਾ',
      'ta': 'தேடல் பயனர்',
      'te': 'శోధన వినియోగదారు',
    },
    '0lrf4y1o': {
      'en': 'Search for users',
      'bn': 'ব্যবহারকারীদের জন্য অনুসন্ধান করুন',
      'hi': 'उपयोगकर्ताओं को खोजें',
      'pa': 'ਉਪਭੋਗਤਾਵਾਂ ਲਈ ਖੋਜ ਕਰੋ',
      'ta': 'பயனர்களைத் தேடுங்கள்',
      'te': 'వినియోగదారుల కోసం శోధించండి',
    },
    '66i48dy7': {
      'en': 'Mummy',
      'bn': 'মমি',
      'hi': 'मां',
      'pa': 'ਮੰਮੀ',
      'ta': 'மம்மி',
      'te': 'మమ్మీ',
    },
    'qe73y15c': {
      'en': 'gritu444@gmail.com',
      'bn': 'gritu444@gmail.com',
      'hi': 'gritu444@gmail.com',
      'pa': 'gritu444@gmail.com',
      'ta': 'gritu444@gmail.com',
      'te': 'gritu444@gmail.com',
    },
    'ckuoepzx': {
      'en': 'Mummy',
      'bn': 'মমি',
      'hi': 'मां',
      'pa': 'ਮੰਮੀ',
      'ta': 'மம்மி',
      'te': 'మమ్మీ',
    },
    'nqep19ix': {
      'en': 'gritu444@gmail.com',
      'bn': 'gritu444@gmail.com',
      'hi': 'gritu444@gmail.com',
      'pa': 'gritu444@gmail.com',
      'ta': 'gritu444@gmail.com',
      'te': 'gritu444@gmail.com',
    },
    '4wvsx5xm': {
      'en': 'Mummy',
      'bn': 'মমি',
      'hi': 'मां',
      'pa': 'ਮੰਮੀ',
      'ta': 'மம்மி',
      'te': 'మమ్మీ',
    },
    'd2bh6q85': {
      'en': 'gritu444@gmail.com',
      'bn': 'gritu444@gmail.com',
      'hi': 'gritu444@gmail.com',
      'pa': 'gritu444@gmail.com',
      'ta': 'gritu444@gmail.com',
      'te': 'gritu444@gmail.com',
    },
    'pq2lzahf': {
      'en': 'Mummy',
      'bn': 'মমি',
      'hi': 'मां',
      'pa': 'ਮੰਮੀ',
      'ta': 'மம்மி',
      'te': 'మమ్మీ',
    },
    '3cjcg1qt': {
      'en': 'gritu444@gmail.com',
      'bn': 'gritu444@gmail.com',
      'hi': 'gritu444@gmail.com',
      'pa': 'gritu444@gmail.com',
      'ta': 'gritu444@gmail.com',
      'te': 'gritu444@gmail.com',
    },
    'ur9kkeo2': {
      'en': 'Home',
      'bn': 'বাড়ি',
      'hi': 'घर',
      'pa': 'ਘਰ',
      'ta': 'வீடு',
      'te': 'హోమ్',
    },
  },
  // chats
  {
    '4oxft6j6': {
      'en': 'type somehing',
      'bn': 'কিছু টাইপ করুন',
      'hi': 'कुछ टाइप करें',
      'pa': 'ਕੁਝ ਟਾਈਪ ਕਰੋ',
      'ta': 'ஏதாவது தட்டச்சு செய்யவும்',
      'te': 'ఏదో టైప్ చేయండి',
    },
    'd1db7t96': {
      'en': 'Home',
      'bn': 'বাড়ি',
      'hi': 'घर',
      'pa': 'ਘਰ',
      'ta': 'வீடு',
      'te': 'హోమ్',
    },
  },
  // Setting
  {
    '2o2ipr7a': {
      'en': 'Edit Profile Pic',
      'bn': 'প্রোফাইল ছবি সম্পাদনা করুন',
      'hi': 'प्रोफ़ाइल चित्र संपादित करें',
      'pa': 'ਪ੍ਰੋਫਾਈਲ ਤਸਵੀਰ ਨੂੰ ਸੰਪਾਦਿਤ ਕਰੋ',
      'ta': 'சுயவிவரப் படத்தைத் திருத்து',
      'te': 'ప్రొఫైల్ చిత్రాన్ని సవరించండి',
    },
    'tsp18p55': {
      'en': 'Account Settings',
      'bn': 'অ্যাকাউন্ট সেটিংস',
      'hi': 'अकाउंट सेटिंग',
      'pa': 'ਖਾਤਾ ਯੋਜਨਾ',
      'ta': 'கணக்கு அமைப்புகள்',
      'te': 'ఖాతా సెట్టింగ్‌లు',
    },
    'r21kj7q0': {
      'en': 'Language Options',
      'bn': 'ভাষার বিকল্প',
      'hi': 'भाषा विकल्प',
      'pa': 'ਭਾਸ਼ਾ ਵਿਕਲਪ',
      'ta': 'மொழி விருப்பங்கள்',
      'te': 'భాషా ఎంపికలు',
    },
    'cdpzidaz': {
      'en': 'Log Out',
      'bn': 'প্রস্থান',
      'hi': 'लॉग आउट',
      'pa': 'ਲਾੱਗ ਆਊਟ, ਬਾਹਰ ਆਉਣਾ',
      'ta': 'வெளியேறு',
      'te': 'లాగ్ అవుట్ చేయండి',
    },
    'dnvi65as': {
      'en': 'Profile',
      'bn': 'প্রোফাইল',
      'hi': 'प्रोफ़ाइल',
      'pa': 'ਪ੍ਰੋਫਾਈਲ',
      'ta': 'சுயவிவரம்',
      'te': 'ప్రొఫైల్',
    },
    '2ovpt7o2': {
      'en': '__',
      'bn': '__',
      'hi': '__',
      'pa': '__',
      'ta': '__',
      'te': '__',
    },
  },
  // animtion
  {
    'dc6r4ypt': {
      'en': 'Home',
      'bn': 'বাড়ি',
      'hi': 'घर',
      'pa': 'ਘਰ',
      'ta': 'வீடு',
      'te': 'హోమ్',
    },
  },
  // login
  {
    'bc10wynd': {
      'en': 'Sign In',
      'bn': 'সাইন ইন করুন',
      'hi': 'दाखिल करना',
      'pa': 'ਸਾਈਨ - ਇਨ',
      'ta': 'உள்நுழையவும்',
      'te': 'సైన్ ఇన్ చేయండి',
    },
    '9wlvoiqh': {
      'en': 'Use the account below to sign in.',
      'bn': 'সাইন ইন করতে নীচের অ্যাকাউন্ট ব্যবহার করুন.',
      'hi': 'साइन इन करने के लिए नीचे दिए गए खाते का उपयोग करें।',
      'pa': 'ਸਾਈਨ ਇਨ ਕਰਨ ਲਈ ਹੇਠਾਂ ਦਿੱਤੇ ਖਾਤੇ ਦੀ ਵਰਤੋਂ ਕਰੋ।',
      'ta': 'உள்நுழைய கீழே உள்ள கணக்கைப் பயன்படுத்தவும்.',
      'te': 'సైన్ ఇన్ చేయడానికి దిగువ ఖాతాను ఉపయోగించండి.',
    },
    'ttivdagc': {
      'en': 'Email',
      'bn': 'ইমেইল',
      'hi': 'ईमेल',
      'pa': 'ਈ - ਮੇਲ',
      'ta': 'மின்னஞ்சல்',
      'te': 'ఇమెయిల్',
    },
    'oux716fq': {
      'en': 'Password',
      'bn': 'পাসওয়ার্ড',
      'hi': 'पासवर्ड',
      'pa': 'ਪਾਸਵਰਡ',
      'ta': 'கடவுச்சொல்',
      'te': 'పాస్వర్డ్',
    },
    'qnn324n0': {
      'en': 'Sign In',
      'bn': 'সাইন ইন করুন',
      'hi': 'दाखिल करना',
      'pa': 'ਸਾਈਨ - ਇਨ',
      'ta': 'உள்நுழையவும்',
      'te': 'సైన్ ఇన్ చేయండి',
    },
    '5tqpp815': {
      'en': 'Forgot Password',
      'bn': 'পাসওয়ার্ড ভুলে গেছেন',
      'hi': 'पासवर्ड भूल गए',
      'pa': 'ਪਾਸਵਰਡ ਭੁੱਲ ਗਏ',
      'ta': 'கடவுச்சொல்லை மறந்துவிட்டீர்களா',
      'te': 'పాస్‌వర్డ్ మర్చిపోయాను',
    },
    '1lzjyzs2': {
      'en': 'Or sign up with',
      'bn': 'অথবা এর সাথে সাইন আপ করুন',
      'hi': 'या इसके साथ साइन अप करें',
      'pa': 'ਜਾਂ ਨਾਲ ਸਾਈਨ ਅੱਪ ਕਰੋ',
      'ta': 'அல்லது உடன் பதிவு செய்யவும்',
      'te': 'లేదా సైన్ అప్ చేయండి',
    },
    'yy397bug': {
      'en': 'Register',
      'bn': 'নিবন্ধন',
      'hi': 'पंजीकरण करवाना',
      'pa': 'ਰਜਿਸਟਰ',
      'ta': 'பதிவு',
      'te': 'నమోదు చేసుకోండి',
    },
    '3jqd9zpl': {
      'en': 'Home',
      'bn': 'বাড়ি',
      'hi': 'घर',
      'pa': 'ਘਰ',
      'ta': 'வீடு',
      'te': 'హోమ్',
    },
  },
  // Register
  {
    'me2l9tru': {
      'en': 'Register',
      'bn': 'নিবন্ধন',
      'hi': 'पंजीकरण करवाना',
      'pa': 'ਰਜਿਸਟਰ',
      'ta': 'பதிவு',
      'te': 'నమోదు చేసుకోండి',
    },
    'i1swichr': {
      'en': 'Use the account below to register.',
      'bn': 'নিবন্ধন করতে নীচের অ্যাকাউন্ট ব্যবহার করুন.',
      'hi': 'पंजीकरण करने के लिए नीचे दिए गए खाते का उपयोग करें।',
      'pa': 'ਰਜਿਸਟਰ ਕਰਨ ਲਈ ਹੇਠਾਂ ਦਿੱਤੇ ਖਾਤੇ ਦੀ ਵਰਤੋਂ ਕਰੋ।',
      'ta': 'பதிவு செய்ய கீழே உள்ள கணக்கைப் பயன்படுத்தவும்.',
      'te': 'నమోదు చేసుకోవడానికి దిగువ ఖాతాను ఉపయోగించండి.',
    },
    'x3r7lno7': {
      'en': 'Name',
      'bn': 'নাম',
      'hi': 'नाम',
      'pa': 'ਨਾਮ',
      'ta': 'பெயர்',
      'te': 'పేరు',
    },
    'x3kxbmui': {
      'en': 'Email',
      'bn': 'ইমেইল',
      'hi': 'ईमेल',
      'pa': 'ਈ - ਮੇਲ',
      'ta': 'மின்னஞ்சல்',
      'te': 'ఇమెయిల్',
    },
    'vdc3ur7c': {
      'en': 'Password',
      'bn': 'পাসওয়ার্ড',
      'hi': 'पासवर्ड',
      'pa': 'ਪਾਸਵਰਡ',
      'ta': 'கடவுச்சொல்',
      'te': 'పాస్వర్డ్',
    },
    'govqndhq': {
      'en': 'Register',
      'bn': 'নিবন্ধন',
      'hi': 'पंजीकरण करवाना',
      'pa': 'ਰਜਿਸਟਰ',
      'ta': 'பதிவு',
      'te': 'నమోదు చేసుకోండి',
    },
    '0rrm51nx': {
      'en': 'Already a user?',
      'bn': 'ইতিমধ্যে একজন ব্যবহারকারী?',
      'hi': 'पहले से ही एक उपयोगकर्ता?',
      'pa': 'ਪਹਿਲਾਂ ਹੀ ਇੱਕ ਉਪਭੋਗਤਾ ਹੈ?',
      'ta': 'ஏற்கனவே ஒரு பயனரா?',
      'te': 'ఇప్పటికే వినియోగదారుగా ఉన్నారా?',
    },
    'lfm1pxbx': {
      'en': 'Home',
      'bn': 'বাড়ি',
      'hi': 'घर',
      'pa': 'ਘਰ',
      'ta': 'வீடு',
      'te': 'హోమ్',
    },
  },
  // start_Animation
  {
    'i7sb5v8c': {
      'en': 'Home',
      'bn': 'বাড়ি',
      'hi': 'घर',
      'pa': 'ਘਰ',
      'ta': 'வீடு',
      'te': 'హోమ్',
    },
  },
  // assistantAi
  {
    't47ot4zt': {
      'en': 'Label here...',
      'bn': 'এখানে লেবেল করুন...',
      'hi': 'यहां लेबल करें...',
      'pa': 'ਇੱਥੇ ਲੇਬਲ ਕਰੋ...',
      'ta': 'இங்கே லேபிளிடு...',
      'te': 'ఇక్కడ లేబుల్ చేయండి...',
    },
    'kn73iodi': {
      'en': 'Button',
      'bn': 'বোতাম',
      'hi': 'बटन',
      'pa': 'ਬਟਨ',
      'ta': 'பொத்தானை',
      'te': 'బటన్',
    },
    'h7re2vdy': {
      'en': 'Home',
      'bn': 'বাড়ি',
      'hi': 'घर',
      'pa': 'ਘਰ',
      'ta': 'வீடு',
      'te': 'హోమ్',
    },
  },
  // chat_interface
  {
    'i1pwcz61': {
      'en': 'Group Chat',
      'bn': 'গ্রুপ চ্যাট',
      'hi': 'समूह बातचीत',
      'pa': 'ਗਰੁੱਪ ਚੈਟ',
      'ta': 'குழு அரட்டை',
      'te': 'గ్రూప్ చాట్',
    },
    '8osvnun7': {
      'en': 'Home',
      'bn': 'বাড়ি',
      'hi': 'घर',
      'pa': 'ਘਰ',
      'ta': 'வீடு',
      'te': 'హోమ్',
    },
  },
  // chat_addUser
  {
    'tsllruh8': {
      'en': 'Invite Friends',
      'bn': 'বন্ধুদের আমন্ত্রণ জানান',
      'hi': 'मित्रों को आमंत्रित करें',
      'pa': 'ਦੋਸਤਾਂ ਨੂੰ ਸੱਦਾ ਦਿਓ',
      'ta': 'நண்பர்களை அழைக்க',
      'te': 'స్నేహితులను ఆహ్వానించండి',
    },
    '5iasfji3': {
      'en': 'Selected',
      'bn': 'নির্বাচিত',
      'hi': 'चयनित',
      'pa': 'ਚੁਣਿਆ ਹੋਇਆ',
      'ta': 'தேர்ந்தெடுக்கப்பட்டது',
      'te': 'ఎంపిక చేయబడింది',
    },
    'ukqk38do': {
      'en': 'Invite Friends',
      'bn': 'বন্ধুদের আমন্ত্রণ জানান',
      'hi': 'मित्रों को आमंत्रित करें',
      'pa': 'ਦੋਸਤਾਂ ਨੂੰ ਸੱਦਾ ਦਿਓ',
      'ta': 'நண்பர்களை அழைக்க',
      'te': 'స్నేహితులను ఆహ్వానించండి',
    },
    'e97g2xum': {
      'en': 'Select users from below to start a chat.',
      'bn': 'একটি চ্যাট শুরু করতে নীচের থেকে ব্যবহারকারীদের নির্বাচন করুন.',
      'hi': 'चैट शुरू करने के लिए नीचे से उपयोगकर्ताओं का चयन करें।',
      'pa': 'ਚੈਟ ਸ਼ੁਰੂ ਕਰਨ ਲਈ ਹੇਠਾਂ ਤੋਂ ਉਪਭੋਗਤਾਵਾਂ ਨੂੰ ਚੁਣੋ।',
      'ta': 'அரட்டையைத் தொடங்க கீழே உள்ள பயனர்களைத் தேர்ந்தெடுக்கவும்.',
      'te': 'చాట్ ప్రారంభించడానికి దిగువ నుండి వినియోగదారులను ఎంచుకోండి.',
    },
    '2j3p4vac': {
      'en': 'Home',
      'bn': 'বাড়ি',
      'hi': 'घर',
      'pa': 'ਘਰ',
      'ta': 'வீடு',
      'te': 'హోమ్',
    },
  },
  // image_Details
  {
    'xj8lputg': {
      'en': 'Home',
      'bn': 'বাড়ি',
      'hi': 'घर',
      'pa': 'ਘਰ',
      'ta': 'வீடு',
      'te': 'హోమ్',
    },
  },
  // PrimaryLangSelect
  {
    'jhti67bi': {
      'en': 'Primary Language',
      'bn': 'প্রাথমিক ভাষা',
      'hi': 'प्राथमिक भाषा',
      'pa': 'ਪ੍ਰਾਇਮਰੀ ਭਾਸ਼ਾ',
      'ta': 'முதன்மை மொழி',
      'te': 'ప్రాథమిక భాష',
    },
    '5uo6ggaw': {
      'en': 'Home',
      'bn': 'বাড়ি',
      'hi': 'घर',
      'pa': 'ਘਰ',
      'ta': 'வீடு',
      'te': 'హోమ్',
    },
  },
  // SecondaryLangSelect
  {
    '8iv5lwgt': {
      'en': 'Secondary Language',
      'bn': 'মাধ্যমিক ভাষা',
      'hi': 'द्वितीयक भाषा',
      'pa': 'ਸੈਕੰਡਰੀ ਭਾਸ਼ਾ',
      'ta': 'இரண்டாம் நிலை மொழி',
      'te': 'ద్వితీయ భాష',
    },
    'pm2ss8aj': {
      'en': 'Home',
      'bn': 'বাড়ি',
      'hi': 'घर',
      'pa': 'ਘਰ',
      'ta': 'வீடு',
      'te': 'హోమ్',
    },
  },
  // UserInformation
  {
    'sr0l10yn': {
      'en': 'Full name*',
      'bn': '',
      'hi': '',
      'pa': '',
      'ta': '',
      'te': '',
    },
    'f4ohmt1c': {
      'en': 'Age*',
      'bn': '',
      'hi': '',
      'pa': '',
      'ta': '',
      'te': '',
    },
    'pdidvr0q': {
      'en': 'Phone number',
      'bn': '',
      'hi': '',
      'pa': '',
      'ta': '',
      'te': '',
    },
    'b7vl1145': {
      'en': 'Date of birth* (dd/mm/yyyy)',
      'bn': '',
      'hi': '',
      'pa': '',
      'ta': '',
      'te': '',
    },
    'saqvblj7': {
      'en': 'Gender',
      'bn': '',
      'hi': '',
      'pa': '',
      'ta': '',
      'te': '',
    },
    '50sgu91a': {
      'en': 'Female',
      'bn': '',
      'hi': '',
      'pa': '',
      'ta': '',
      'te': '',
    },
    '29bvgdg2': {
      'en': 'Male',
      'bn': '',
      'hi': '',
      'pa': '',
      'ta': '',
      'te': '',
    },
    '1qvdevrw': {
      'en': 'Other',
      'bn': '',
      'hi': '',
      'pa': '',
      'ta': '',
      'te': '',
    },
    '51ic99uf': {
      'en': 'About',
      'bn': '',
      'hi': '',
      'pa': '',
      'ta': '',
      'te': '',
    },
    'iony6ghi': {
      'en': 'Please describe you ',
      'bn': '',
      'hi': '',
      'pa': '',
      'ta': '',
      'te': '',
    },
    'p6n7hoz2': {
      'en': 'Continue',
      'bn': '',
      'hi': '',
      'pa': '',
      'ta': '',
      'te': '',
    },
    'dzv90fyh': {
      'en': 'Please enter the patients full name.',
      'bn': '',
      'hi': '',
      'pa': '',
      'ta': '',
      'te': '',
    },
    'zai8plme': {
      'en': 'Please choose an option from the dropdown',
      'bn': '',
      'hi': '',
      'pa': '',
      'ta': '',
      'te': '',
    },
    'ld3t85k3': {
      'en': 'Please enter an age for the patient.',
      'bn': '',
      'hi': '',
      'pa': '',
      'ta': '',
      'te': '',
    },
    '57ynb6dr': {
      'en': 'Please choose an option from the dropdown',
      'bn': '',
      'hi': '',
      'pa': '',
      'ta': '',
      'te': '',
    },
    'ekg6deuj': {
      'en': 'Please choose an option from the dropdown',
      'bn': '',
      'hi': '',
      'pa': '',
      'ta': '',
      'te': '',
    },
    'ponooxv0': {
      'en': 'Please enter the date of birth of the patient.',
      'bn': '',
      'hi': '',
      'pa': '',
      'ta': '',
      'te': '',
    },
    'iadc44eq': {
      'en': 'Please choose an option from the dropdown',
      'bn': '',
      'hi': '',
      'pa': '',
      'ta': '',
      'te': '',
    },
    'gjy3450j': {
      'en': 'Field is required',
      'bn': '',
      'hi': '',
      'pa': '',
      'ta': '',
      'te': '',
    },
    'r173ob31': {
      'en': 'Please choose an option from the dropdown',
      'bn': '',
      'hi': '',
      'pa': '',
      'ta': '',
      'te': '',
    },
    'o4lahbk0': {
      'en': 'Your Account',
      'bn': '',
      'hi': '',
      'pa': '',
      'ta': '',
      'te': '',
    },
    'keqbaxiz': {
      'en': 'Please fill out the information  below to continue.',
      'bn': '',
      'hi': '',
      'pa': '',
      'ta': '',
      'te': '',
    },
    'jout30zu': {
      'en': 'Home',
      'bn': 'বাড়ি',
      'hi': 'घर',
      'pa': 'ਘਰ',
      'ta': 'வீடு',
      'te': 'హోమ్',
    },
  },
  // ai_text
  {
    'lqpksn3m': {
      'en': 'AksharAI',
      'bn': 'অক্ষরএআই',
      'hi': 'अक्षराई',
      'pa': 'ਅਕਸ਼ਰਏ.ਆਈ',
      'ta': 'அக்ஷராஐ',
      'te': 'అక్షరఏఐ',
    },
    '0l0san8a': {
      'en': 'Text',
      'bn': 'পাঠ্য',
      'hi': 'मूलपाठ',
      'pa': 'ਟੈਕਸਟ',
      'ta': 'உரை',
      'te': 'వచనం',
    },
    'n1bhjatm': {
      'en': 'Image',
      'bn': 'ছবি',
      'hi': 'छवि',
      'pa': 'ਚਿੱਤਰ',
      'ta': 'படம்',
      'te': 'చిత్రం',
    },
    'sbjce0qa': {
      'en': 'Generate From',
      'bn': 'থেকে তৈরি করুন',
      'hi': 'से उत्पन्न करें',
      'pa': 'ਤੋਂ ਤਿਆਰ ਕਰੋ',
      'ta': 'இருந்து உருவாக்கு',
      'te': 'నుండి రూపొందించండి',
    },
    'lsgfb342': {
      'en':
          'AksharAI  is a powerfull AI assistant which can easily answer your questions and generates solutions from images also\n\nIn your prefered language.  \n',
      'bn':
          'AksharAI হল Google-এর Gemini দ্বারা চালিত একটি শক্তিশালী AI সহকারী যা সহজেই আপনার প্রশ্নের উত্তর দিতে পারে এবং ছবিও তৈরি করে',
      'hi':
          'अक्षरएआई Google के जेमिनी द्वारा संचालित एक शक्तिशाली एआई सहायक है जो आसानी से आपके प्रश्न का उत्तर दे सकता है और छवियां भी उत्पन्न कर सकता है',
      'pa':
          'ਅਕਸ਼ਰਏਆਈ ਗੂਗਲ ਦੇ ਜੈਮਿਨੀ ਦੁਆਰਾ ਸੰਚਾਲਿਤ ਇੱਕ ਸ਼ਕਤੀਸ਼ਾਲੀ AI ਸਹਾਇਕ ਹੈ ਜੋ ਆਸਾਨੀ ਨਾਲ ਤੁਹਾਡੇ ਸਵਾਲ ਦਾ ਜਵਾਬ ਦੇ ਸਕਦਾ ਹੈ ਅਤੇ ਚਿੱਤਰ ਵੀ ਤਿਆਰ ਕਰਦਾ ਹੈ',
      'ta':
          'அக்ஷராஐ என்பது கூகிளின் ஜெமினியால் இயக்கப்படும் ஒரு சக்திவாய்ந்த AI உதவியாளர், இது உங்கள் கேள்விக்கு எளிதாக பதிலளிக்கும் மற்றும் படங்களையும் உருவாக்குகிறது.',
      'te':
          'AksharAI అనేది Google యొక్క జెమిని ద్వారా ఆధారితమైన శక్తివంతమైన AI సహాయకం, ఇది మీ ప్రశ్నకు సులభంగా సమాధానం ఇవ్వగలదు మరియు చిత్రాలను కూడా రూపొందించగలదు.',
    },
    'q06wdtdx': {
      'en': 'Home',
      'bn': 'বাড়ি',
      'hi': 'घर',
      'pa': 'ਘਰ',
      'ta': 'வீடு',
      'te': 'హోమ్',
    },
  },
  // text_generate
  {
    'e4wuyps5': {
      'en': 'AksharAI',
      'bn': 'অক্ষরএআই',
      'hi': 'अक्षराई',
      'pa': 'ਅਕਸ਼ਰਏ.ਆਈ',
      'ta': 'அக்ஷராஐ',
      'te': 'అక్షరఏఐ',
    },
    'zvbi8ka7': {
      'en': 'Text',
      'bn': 'পাঠ্য',
      'hi': 'मूलपाठ',
      'pa': 'ਟੈਕਸਟ',
      'ta': 'உரை',
      'te': 'వచనం',
    },
    'dfapz6u7': {
      'en': 'Text',
      'bn': 'পাঠ্য',
      'hi': 'मूलपाठ',
      'pa': 'ਟੈਕਸਟ',
      'ta': 'உரை',
      'te': 'వచనం',
    },
    '5mfhyjy1': {
      'en': 'Image',
      'bn': 'ছবি',
      'hi': 'छवि',
      'pa': 'ਚਿੱਤਰ',
      'ta': 'படம்',
      'te': 'చిత్రం',
    },
    'vjrr4fru': {
      'en': 'Generate From',
      'bn': 'থেকে তৈরি করুন',
      'hi': 'से उत्पन्न करें',
      'pa': 'ਤੋਂ ਤਿਆਰ ਕਰੋ',
      'ta': 'இருந்து உருவாக்கு',
      'te': 'నుండి రూపొందించండి',
    },
    'b00jm31m': {
      'en': 'Label here...',
      'bn': 'এখানে লেবেল করুন...',
      'hi': 'यहां लेबल करें...',
      'pa': 'ਇੱਥੇ ਲੇਬਲ ਕਰੋ...',
      'ta': 'இங்கே லேபிளிடு...',
      'te': 'ఇక్కడ లేబుల్ చేయండి...',
    },
    '8fb6xogm': {
      'en': 'Home',
      'bn': 'বাড়ি',
      'hi': 'घर',
      'pa': 'ਘਰ',
      'ta': 'வீடு',
      'te': 'హోమ్',
    },
  },
  // Primary_Language
  {
    'l4o57wmo': {
      'en': 'Choose your first languge',
      'bn': 'আপনার প্রথম ভাষা চয়ন করুন',
      'hi': 'अपनी पहली भाषा चुनें',
      'pa': 'ਆਪਣੀ ਪਹਿਲੀ ਭਾਸ਼ਾ ਚੁਣੋ',
      'ta': 'உங்கள் முதல் மொழியைத் தேர்ந்தெடுக்கவும்',
      'te': 'మీ మొదటి భాషను ఎంచుకోండి',
    },
    '0ck0cxdh': {
      'en': 'English',
      'bn': 'ইংরেজি',
      'hi': 'अंग्रेज़ी',
      'pa': 'ਅੰਗਰੇਜ਼ੀ',
      'ta': 'ஆங்கிலம்',
      'te': 'ఆంగ్ల',
    },
    'cfiwayms': {
      'en': 'हिंदी  (Hindi)',
      'bn': 'হিন্দি (হিন্দি)',
      'hi': 'हिंदी (हिन्दी)',
      'pa': 'ਹਿੰਦੀ (ਹਿੰਦੀ)',
      'ta': 'हिंदी (ஹிந்தி)',
      'te': 'హిందీ (హిందీ)',
    },
    'adxotwx9': {
      'en': 'English',
      'bn': 'ইংরেজি',
      'hi': 'अंग्रेज़ी',
      'pa': 'ਅੰਗਰੇਜ਼ੀ',
      'ta': 'ஆங்கிலம்',
      'te': 'ఆంగ్ల',
    },
    '12lqtcwq': {
      'en': 'ਪੰਜਾਬੀ  (Punjabi)',
      'bn': 'পাঞ্জাবী (পাঞ্জাবি)',
      'hi': 'ਪੰਜਾਬੀ (पंजाबी)',
      'pa': 'ਪੰਜਾਬੀ (ਪੰਜਾਬੀ)',
      'ta': 'பிரஜாபி (பஞ்சாபி)',
      'te': 'ప్రజాబి (పంజాబీ)',
    },
    '4nsvpwb5': {
      'en': 'తెలుగు  (Telugu)',
      'bn': 'తెలుగు (তেলেগু)',
      'hi': 'తెలుగు (तेलुगु)',
      'pa': 'తెలుగు (ਤੇਲਗੂ)',
      'ta': 'தெலுங்கு (தெலுங்கு)',
      'te': 'తెలుగు (తెలుగు)',
    },
    'y4jxiidi': {
      'en': 'বাংলা  (Bangla)',
      'bn': 'বাংলা (বাংলা)',
      'hi': 'বাংলা (बांग्ला)',
      'pa': 'বাংলা (ਬੰਗਲਾ)',
      'ta': 'বাংলা (பங்களா)',
      'te': 'বাংলা (బంగ్లా)',
    },
    'rpjuqw0j': {
      'en': 'தமிழ்  (Tamil)',
      'bn': 'தமிழ் (তামিল)',
      'hi': 'தமிழ் (तमिल)',
      'pa': 'தமிழ் (ਤਮਿਲ)',
      'ta': 'தமிழ் (தமிழ்)',
      'te': 'తమిళం (తమిళం)',
    },
    '823b9wm1': {
      'en': 'Next',
      'bn': 'পরবর্তী',
      'hi': 'अगला',
      'pa': 'ਅਗਲਾ',
      'ta': 'அடுத்தது',
      'te': 'తరువాత',
    },
  },
  // chat_Setting
  {
    'txm40tis': {
      'en': 'View',
      'bn': 'দেখুন',
      'hi': 'देखना',
      'pa': 'ਦੇਖੋ',
      'ta': 'காண்க',
      'te': 'చూడండి',
    },
    'fuv4rbpt': {
      'en': 'Translate',
      'bn': 'অনুবাদ করা',
      'hi': 'अनुवाद',
      'pa': 'ਅਨੁਵਾਦ',
      'ta': 'மொழிபெயர்',
      'te': 'అనువదించు',
    },
    'c7dhakjp': {
      'en': 'Search',
      'bn': 'অনুসন্ধান করুন',
      'hi': 'खोज',
      'pa': 'ਖੋਜ',
      'ta': 'தேடு',
      'te': 'వెతకండి',
    },
    '7dpb27c9': {
      'en': 'Delete',
      'bn': 'মুছে ফেলা',
      'hi': 'मिटाना',
      'pa': 'ਮਿਟਾਓ',
      'ta': 'அழி',
      'te': 'తొలగించు',
    },
  },
  // Secondary_Language
  {
    'a05kb581': {
      'en': 'Choose your alternative languge',
      'bn': 'আপনার বিকল্প ভাষা চয়ন করুন',
      'hi': 'अपनी वैकल्पिक भाषा चुनें',
      'pa': 'ਆਪਣੀ ਬਦਲਵੀਂ ਭਾਸ਼ਾ ਚੁਣੋ',
      'ta': 'உங்கள் மாற்று மொழியை தேர்வு செய்யவும்',
      'te': 'మీ ప్రత్యామ్నాయ భాషను ఎంచుకోండి',
    },
    'm0jntuhq': {
      'en': 'English',
      'bn': 'ইংরেজি',
      'hi': 'अंग्रेज़ी',
      'pa': 'ਅੰਗਰੇਜ਼ੀ',
      'ta': 'ஆங்கிலம்',
      'te': 'ఆంగ్ల',
    },
    'mse710rl': {
      'en': 'हिंदी  (Hindi)',
      'bn': 'হিন্দি (হিন্দি)',
      'hi': 'हिंदी (हिन्दी)',
      'pa': 'ਹਿੰਦੀ (ਹਿੰਦੀ)',
      'ta': 'हिंदी (ஹிந்தி)',
      'te': 'హిందీ (హిందీ)',
    },
    'xb8maa17': {
      'en': 'English',
      'bn': 'ইংরেজি',
      'hi': 'अंग्रेज़ी',
      'pa': 'ਅੰਗਰੇਜ਼ੀ',
      'ta': 'ஆங்கிலம்',
      'te': 'ఆంగ్ల',
    },
    'edbw7t5q': {
      'en': 'ਪੰਜਾਬੀ  (Punjabi)',
      'bn': 'পাঞ্জাবী (পাঞ্জাবি)',
      'hi': 'ਪੰਜਾਬੀ (पंजाबी)',
      'pa': 'ਪੰਜਾਬੀ (ਪੰਜਾਬੀ)',
      'ta': 'பிரஜாபி (பஞ்சாபி)',
      'te': 'ప్రజాబి (పంజాబీ)',
    },
    'tnof8tba': {
      'en': 'తెలుగు  (Telugu)',
      'bn': 'తెలుగు (তেলেগু)',
      'hi': 'తెలుగు (तेलुगु)',
      'pa': 'తెలుగు (ਤੇਲਗੂ)',
      'ta': 'தெலுங்கு (தெலுங்கு)',
      'te': 'తెలుగు (తెలుగు)',
    },
    'tzleoeeh': {
      'en': 'বাংলা  (Bangla)',
      'bn': 'বাংলা (বাংলা)',
      'hi': 'বাংলা (बांग्ला)',
      'pa': 'বাংলা (ਬੰਗਲਾ)',
      'ta': 'বাংলা (பங்களா)',
      'te': 'বাংলা (బంగ్లా)',
    },
    'c7ggfbez': {
      'en': 'தமிழ்  (Tamil)',
      'bn': 'தமிழ் (তামিল)',
      'hi': 'தமிழ் (तमिल)',
      'pa': 'தமிழ் (ਤਮਿਲ)',
      'ta': 'தமிழ் (தமிழ்)',
      'te': 'తమిళం (తమిళం)',
    },
    'ci1uki0i': {
      'en': 'Next',
      'bn': 'পরবর্তী',
      'hi': 'अगला',
      'pa': 'ਅਗਲਾ',
      'ta': 'அடுத்தது',
      'te': 'తరువాత',
    },
  },
  // DarkLightSwitch
  {
    'hmx7dtwq': {
      'en': 'Light Mode',
      'bn': 'হালকা মোড',
      'hi': 'लाइट मोड',
      'pa': 'ਲਾਈਟ ਮੋਡ',
      'ta': 'ஒளி முறை',
      'te': 'లైట్ మోడ్',
    },
    'pr5wlia2': {
      'en': 'Dark Mode',
      'bn': 'ডার্ক মোড',
      'hi': 'डार्क मोड',
      'pa': 'ਡਾਰਕ ਮੋਡ',
      'ta': 'இருண்ட பயன்முறை',
      'te': 'డార్క్ మోడ్',
    },
  },
  // Generate_Text
  {
    '00v2afo1': {
      'en': 'AksharAI',
      'bn': 'অক্ষরএআই',
      'hi': 'अक्षराई',
      'pa': 'ਅਕਸ਼ਰਏ.ਆਈ',
      'ta': 'அக்ஷராஐ',
      'te': 'అక్షరఏఐ',
    },
    'zba7f6wt': {
      'en': 'Text',
      'bn': 'পাঠ্য',
      'hi': 'मूलपाठ',
      'pa': 'ਟੈਕਸਟ',
      'ta': 'உரை',
      'te': 'వచనం',
    },
    'v4pmvzvu': {
      'en': 'Text',
      'bn': 'পাঠ্য',
      'hi': 'मूलपाठ',
      'pa': 'ਟੈਕਸਟ',
      'ta': 'உரை',
      'te': 'వచనం',
    },
    'u440vbyr': {
      'en': 'Image',
      'bn': 'ছবি',
      'hi': 'छवि',
      'pa': 'ਚਿੱਤਰ',
      'ta': 'படம்',
      'te': 'చిత్రం',
    },
    'nliy1c1p': {
      'en': 'Generate From',
      'bn': 'থেকে তৈরি করুন',
      'hi': 'से उत्पन्न करें',
      'pa': 'ਤੋਂ ਤਿਆਰ ਕਰੋ',
      'ta': 'இருந்து உருவாக்கு',
      'te': 'నుండి రూపొందించండి',
    },
    'n2hoa59a': {
      'en': 'Label here...',
      'bn': 'এখানে লেবেল করুন...',
      'hi': 'यहां लेबल करें...',
      'pa': 'ਇੱਥੇ ਲੇਬਲ ਕਰੋ...',
      'ta': 'இங்கே லேபிளிடு...',
      'te': 'ఇక్కడ లేబుల్ చేయండి...',
    },
  },
  // aksharAi_INTRO
  {
    '64l1qrbi': {
      'en': 'AksharAI',
      'bn': 'অক্ষরএআই',
      'hi': 'अक्षराई',
      'pa': 'ਅਕਸ਼ਰਏ.ਆਈ',
      'ta': 'அக்ஷராஐ',
      'te': 'అక్షరఏఐ',
    },
    'upfqok40': {
      'en': 'Text',
      'bn': 'পাঠ্য',
      'hi': 'मूलपाठ',
      'pa': 'ਟੈਕਸਟ',
      'ta': 'உரை',
      'te': 'వచనం',
    },
    'x5c85iko': {
      'en': 'Image',
      'bn': 'ছবি',
      'hi': 'छवि',
      'pa': 'ਚਿੱਤਰ',
      'ta': 'படம்',
      'te': 'చిత్రం',
    },
    '5cnuqcbi': {
      'en': 'Generate From',
      'bn': 'থেকে তৈরি করুন',
      'hi': 'से उत्पन्न करें',
      'pa': 'ਤੋਂ ਤਿਆਰ ਕਰੋ',
      'ta': 'இருந்து உருவாக்கு',
      'te': 'నుండి రూపొందించండి',
    },
    'hwvso7vz': {
      'en':
          'AksharAI  is a powerfull AI assistant which can easily answer your questions and generates solutions from images also\n\nIn your prefered language.  \n',
      'bn':
          'AksharAI হল Google-এর Gemini দ্বারা চালিত একটি শক্তিশালী AI সহকারী যা সহজেই আপনার প্রশ্নের উত্তর দিতে পারে এবং ছবিও তৈরি করে',
      'hi':
          'अक्षरएआई Google के जेमिनी द्वारा संचालित एक शक्तिशाली एआई सहायक है जो आसानी से आपके प्रश्न का उत्तर दे सकता है और छवियां भी उत्पन्न कर सकता है',
      'pa':
          'ਅਕਸ਼ਰਏਆਈ ਗੂਗਲ ਦੇ ਜੈਮਿਨੀ ਦੁਆਰਾ ਸੰਚਾਲਿਤ ਇੱਕ ਸ਼ਕਤੀਸ਼ਾਲੀ AI ਸਹਾਇਕ ਹੈ ਜੋ ਆਸਾਨੀ ਨਾਲ ਤੁਹਾਡੇ ਸਵਾਲ ਦਾ ਜਵਾਬ ਦੇ ਸਕਦਾ ਹੈ ਅਤੇ ਚਿੱਤਰ ਵੀ ਤਿਆਰ ਕਰਦਾ ਹੈ',
      'ta':
          'அக்ஷராஐ என்பது கூகிளின் ஜெமினியால் இயக்கப்படும் ஒரு சக்திவாய்ந்த AI உதவியாளர், இது உங்கள் கேள்விக்கு எளிதாக பதிலளிக்கும் மற்றும் படங்களையும் உருவாக்குகிறது.',
      'te':
          'AksharAI అనేది Google యొక్క జెమిని ద్వారా ఆధారితమైన శక్తివంతమైన AI సహాయకం, ఇది మీ ప్రశ్నకు సులభంగా సమాధానం ఇవ్వగలదు మరియు చిత్రాలను కూడా రూపొందించగలదు.',
    },
  },
  // Generate_Image
  {
    'fo442e95': {
      'en': 'AksharAI',
      'bn': 'অক্ষরএআই',
      'hi': 'अक्षराई',
      'pa': 'ਅਕਸ਼ਰਏ.ਆਈ',
      'ta': 'அக்ஷராஐ',
      'te': 'అక్షరఏఐ',
    },
    'pzucgr05': {
      'en': 'Image ',
      'bn': 'ছবি',
      'hi': 'छवि',
      'pa': 'ਚਿੱਤਰ',
      'ta': 'படம்',
      'te': 'చిత్రం',
    },
    '1b94bk81': {
      'en': 'Text',
      'bn': 'পাঠ্য',
      'hi': 'मूलपाठ',
      'pa': 'ਟੈਕਸਟ',
      'ta': 'உரை',
      'te': 'వచనం',
    },
    'pz2bhgye': {
      'en': 'Image ',
      'bn': 'ছবি',
      'hi': 'छवि',
      'pa': 'ਚਿੱਤਰ',
      'ta': 'படம்',
      'te': 'చిత్రం',
    },
    '40k6sx06': {
      'en': 'Generate from',
      'bn': 'থেকে তৈরি করুন',
      'hi': 'से उत्पन्न करें',
      'pa': 'ਤੋਂ ਤਿਆਰ ਕਰੋ',
      'ta': 'இருந்து உருவாக்கவும்',
      'te': 'నుండి రూపొందించండి',
    },
    'zm28n3rc': {
      'en': 'Label here...',
      'bn': 'এখানে লেবেল করুন...',
      'hi': 'यहां लेबल करें...',
      'pa': 'ਇੱਥੇ ਲੇਬਲ ਕਰੋ...',
      'ta': 'இங்கே லேபிளிடு...',
      'te': 'ఇక్కడ లేబుల్ చేయండి...',
    },
  },
  // chat_Setting_Overlay
  {
    'vu4b712a': {
      'en': 'Chat Details',
      'bn': 'চ্যাট বিবরণ',
      'hi': 'चैट विवरण',
      'pa': 'ਚੈਟ ਵੇਰਵੇ',
      'ta': 'அரட்டை விவரங்கள்',
      'te': 'చాట్ వివరాలు',
    },
    'jg9zqol6': {
      'en': 'Group Chat ID: ',
      'bn': 'গ্রুপ চ্যাট আইডি:',
      'hi': 'समूह चैट आईडी:',
      'pa': 'ਗਰੁੱਪ ਚੈਟ ID:',
      'ta': 'குழு அரட்டை ஐடி:',
      'te': 'గ్రూప్ చాట్ ID:',
    },
    '851drton': {
      'en': 'In this chat',
      'bn': 'এই আড্ডায়',
      'hi': 'इस चैट में',
      'pa': 'ਇਸ ਗੱਲਬਾਤ ਵਿੱਚ',
      'ta': 'இந்த அரட்டையில்',
      'te': 'ఈ చాట్‌లో',
    },
    'hyvnua8c': {
      'en': 'Close',
      'bn': 'বন্ধ',
      'hi': 'बंद करना',
      'pa': 'ਬੰਦ ਕਰੋ',
      'ta': 'நெருக்கமான',
      'te': 'దగ్గరగా',
    },
  },
  // chat_Component
  {
    'zljrmqlc': {
      'en': 'Start typing here...',
      'bn': 'এখানে টাইপ করা শুরু করুন...',
      'hi': 'यहां टाइप करना प्रारंभ करें...',
      'pa': 'ਇੱਥੇ ਟਾਈਪ ਕਰਨਾ ਸ਼ੁਰੂ ਕਰੋ...',
      'ta': 'இங்கே தட்டச்சு செய்யத் தொடங்கு...',
      'te': 'ఇక్కడ టైప్ చేయడం ప్రారంభించండి...',
    },
    'nm6flly2': {
      'en': 'You must enter a message...',
      'bn': 'আপনাকে অবশ্যই একটি বার্তা লিখতে হবে...',
      'hi': 'आपको एक संदेश दर्ज करना होगा...',
      'pa': 'ਤੁਹਾਨੂੰ ਇੱਕ ਸੁਨੇਹਾ ਦਾਖਲ ਕਰਨਾ ਚਾਹੀਦਾ ਹੈ...',
      'ta': 'நீங்கள் ஒரு செய்தியை உள்ளிட வேண்டும்...',
      'te': 'మీరు తప్పనిసరిగా సందేశాన్ని నమోదు చేయాలి...',
    },
    'depzx262': {
      'en': 'Please choose an option from the dropdown',
      'bn': 'ড্রপডাউন থেকে একটি বিকল্প চয়ন করুন',
      'hi': 'कृपया ड्रॉपडाउन से एक विकल्प चुनें',
      'pa': 'ਕਿਰਪਾ ਕਰਕੇ ਡ੍ਰੌਪਡਾਉਨ ਵਿੱਚੋਂ ਇੱਕ ਵਿਕਲਪ ਚੁਣੋ',
      'ta': 'கீழ்தோன்றலில் இருந்து ஒரு விருப்பத்தைத் தேர்ந்தெடுக்கவும்',
      'te': 'దయచేసి డ్రాప్‌డౌన్ నుండి ఒక ఎంపికను ఎంచుకోండి',
    },
  },
  // user_ListSmall
  {
    'xpittvnb': {
      'en': 'ME',
      'bn': 'আমাকে',
      'hi': 'मुझे',
      'pa': 'ME',
      'ta': 'ME',
      'te': 'ME',
    },
  },
  // deleteDialog
  {
    'p4e5a30u': {
      'en': 'Chat Settings',
      'bn': 'চ্যাট সেটিংস',
      'hi': 'चैट सेटिंग्स',
      'pa': 'ਚੈਟ ਸੈਟਿੰਗਾਂ',
      'ta': 'அரட்டை அமைப்புகள்',
      'te': 'చాట్ సెట్టింగ్‌లు',
    },
    'thqvsvt3': {
      'en': 'Language Setting',
      'bn': 'ভাষা সেটিং',
      'hi': 'भाषा सेटिंग',
      'pa': 'ਭਾਸ਼ਾ ਸੈਟਿੰਗ',
      'ta': 'மொழி அமைப்பு',
      'te': 'భాష సెట్టింగ్',
    },
    'jo7lwk7j': {
      'en': 'Options',
      'bn': 'অপশন',
      'hi': 'विकल्प',
      'pa': 'ਵਿਕਲਪ',
      'ta': 'விருப்பங்கள்',
      'te': 'ఎంపికలు',
    },
    'smy8hehj': {
      'en': 'Invite Users',
      'bn': 'ব্যবহারকারীদের আমন্ত্রণ',
      'hi': 'उपयोगकर्ताओं को आमंत्रित करें',
      'pa': 'ਉਪਭੋਗਤਾਵਾਂ ਨੂੰ ਸੱਦਾ ਦਿਓ',
      'ta': 'பயனர்களை அழைக்கவும்',
      'te': 'వినియోగదారులను ఆహ్వానించండి',
    },
    'mn7p878h': {
      'en': 'Delete Chat',
      'bn': 'চ্যাট মুছুন',
      'hi': 'चैट हटाएँ',
      'pa': 'ਚੈਟ ਮਿਟਾਓ',
      'ta': 'அரட்டையை நீக்கு',
      'te': 'చాట్‌ని తొలగించండి',
    },
    'sbj0gi2f': {
      'en': 'Confirm Delete',
      'bn': 'নিশ্চিত বাতিল',
      'hi': 'हटाने की पुष्टि करें',
      'pa': 'ਮਿਟਾਉਣ ਦੀ ਪੁਸ਼ਟੀ ਕਰੋ',
      'ta': 'நீக்குவதை உறுதிப்படுத்தவும்',
      'te': 'తొలగించడాన్ని నిర్ధారించండి',
    },
    'z4ta2494': {
      'en': 'You can\'t undo this action.',
      'bn': 'আপনি এই ক্রিয়াটিকে পূর্বাবস্থায় ফেরাতে পারবেন না৷',
      'hi': 'आप इस क्रिया को पूर्ववत नहीं कर सकते.',
      'pa': 'ਤੁਸੀਂ ਇਸ ਕਾਰਵਾਈ ਨੂੰ ਅਣਕੀਤਾ ਨਹੀਂ ਕਰ ਸਕਦੇ।',
      'ta': 'இந்தச் செயலைச் செயல்தவிர்க்க முடியாது.',
      'te': 'మీరు ఈ చర్యను రద్దు చేయలేరు.',
    },
    '6464jnvw': {
      'en': 'Delete',
      'bn': 'মুছে ফেলা',
      'hi': 'मिटाना',
      'pa': 'ਮਿਟਾਓ',
      'ta': 'அழி',
      'te': 'తొలగించు',
    },
  },
  // tut
  {
    'gh5ojjpl': {
      'en': 'Akshar',
      'bn': 'অক্ষরএআই',
      'hi': 'अक्षराई',
      'pa': 'ਅਕਸ਼ਰਏ.ਆਈ',
      'ta': 'அக்ஷராஐ',
      'te': 'అక్షరఏఐ',
    },
  },
  // Miscellaneous
  {
    'guy0hptf': {
      'en': '',
      'bn': '',
      'hi': '',
      'pa': '',
      'ta': '',
      'te': '',
    },
    'ois8yn8h': {
      'en': '',
      'bn': '',
      'hi': '',
      'pa': '',
      'ta': '',
      'te': '',
    },
    '5abnovat': {
      'en': 'Allow this app access to photp library to share media',
      'bn':
          'মিডিয়া শেয়ার করতে এই অ্যাপটিকে photp লাইব্রেরিতে অ্যাক্সেসের অনুমতি দিন',
      'hi':
          'मीडिया साझा करने के लिए इस ऐप को फोटो लाइब्रेरी तक पहुंच की अनुमति दें',
      'pa': 'ਮੀਡੀਆ ਨੂੰ ਸਾਂਝਾ ਕਰਨ ਲਈ ਇਸ ਐਪ ਨੂੰ photp ਲਾਇਬ੍ਰੇਰੀ ਤੱਕ ਪਹੁੰਚ ਦਿਓ',
      'ta': 'மீடியாவைப் பகிர, இந்த ஆப்ஸை photp நூலகத்தை அணுக அனுமதிக்கவும்',
      'te':
          'మీడియాను భాగస్వామ్యం చేయడానికి photp లైబ్రరీకి ఈ యాప్ యాక్సెస్‌ని అనుమతించండి',
    },
    'ojb9z904': {
      'en': '',
      'bn': '',
      'hi': '',
      'pa': '',
      'ta': '',
      'te': '',
    },
    'rp18nfyr': {
      'en': '',
      'bn': '',
      'hi': '',
      'pa': '',
      'ta': '',
      'te': '',
    },
    'vg4gxtaf': {
      'en': '',
      'bn': '',
      'hi': '',
      'pa': '',
      'ta': '',
      'te': '',
    },
    'ogsavz2g': {
      'en': '',
      'bn': '',
      'hi': '',
      'pa': '',
      'ta': '',
      'te': '',
    },
    'n8cepfws': {
      'en': '',
      'bn': '',
      'hi': '',
      'pa': '',
      'ta': '',
      'te': '',
    },
    'vehm6crc': {
      'en': '',
      'bn': '',
      'hi': '',
      'pa': '',
      'ta': '',
      'te': '',
    },
    'orukk9p3': {
      'en': '',
      'bn': '',
      'hi': '',
      'pa': '',
      'ta': '',
      'te': '',
    },
    'k6u1iwuz': {
      'en': '',
      'bn': '',
      'hi': '',
      'pa': '',
      'ta': '',
      'te': '',
    },
    '4m0smhfy': {
      'en': '',
      'bn': '',
      'hi': '',
      'pa': '',
      'ta': '',
      'te': '',
    },
    'zgbtblam': {
      'en': '',
      'bn': '',
      'hi': '',
      'pa': '',
      'ta': '',
      'te': '',
    },
    '1zegld0s': {
      'en': '',
      'bn': '',
      'hi': '',
      'pa': '',
      'ta': '',
      'te': '',
    },
    'fixl5up3': {
      'en': '',
      'bn': '',
      'hi': '',
      'pa': '',
      'ta': '',
      'te': '',
    },
    '10312oal': {
      'en': '',
      'bn': '',
      'hi': '',
      'pa': '',
      'ta': '',
      'te': '',
    },
    '7ikpv620': {
      'en': '',
      'bn': '',
      'hi': '',
      'pa': '',
      'ta': '',
      'te': '',
    },
    '80dxzyrr': {
      'en': '',
      'bn': '',
      'hi': '',
      'pa': '',
      'ta': '',
      'te': '',
    },
    'k8o2kmqa': {
      'en': '',
      'bn': '',
      'hi': '',
      'pa': '',
      'ta': '',
      'te': '',
    },
    'yivrdz8l': {
      'en': '',
      'bn': '',
      'hi': '',
      'pa': '',
      'ta': '',
      'te': '',
    },
    'l9cdep0v': {
      'en': '',
      'bn': '',
      'hi': '',
      'pa': '',
      'ta': '',
      'te': '',
    },
    'uq9k0o2b': {
      'en': '',
      'bn': '',
      'hi': '',
      'pa': '',
      'ta': '',
      'te': '',
    },
    '0isqevvq': {
      'en': '',
      'bn': '',
      'hi': '',
      'pa': '',
      'ta': '',
      'te': '',
    },
    'j79i425h': {
      'en': '',
      'bn': '',
      'hi': '',
      'pa': '',
      'ta': '',
      'te': '',
    },
    'kcpcdmd9': {
      'en': '',
      'bn': '',
      'hi': '',
      'pa': '',
      'ta': '',
      'te': '',
    },
    'muyx4j24': {
      'en': '',
      'bn': '',
      'hi': '',
      'pa': '',
      'ta': '',
      'te': '',
    },
    '5qz6dmdb': {
      'en': '',
      'bn': '',
      'hi': '',
      'pa': '',
      'ta': '',
      'te': '',
    },
    'jar3hggq': {
      'en': '',
      'bn': '',
      'hi': '',
      'pa': '',
      'ta': '',
      'te': '',
    },
  },
].reduce((a, b) => a..addAll(b));
